services:
  db_dev:
    image: postgis/postgis:15-3.3
    container_name: postgis_dev
    environment:
      POSTGRES_PASSWORD: senha_dev
      POSTGRES_DB: postgis
    ports:
      - "5435:5432"
    volumes:
      - ./pgdata_dev:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    logging:
      driver: "json-file"
      options:
        max-size: "10mb"
