-- TABELA: catalogos.tipo_material_rede_agua (Water Main Material)
INSERT INTO catalogos.tipo_material_rede_agua (codigo, descricao, detalhes)
VALUES
    (1,  'Cimento-Amianto (CA)',                 'Obsoleto/Manutenção - NBR 6422'),
    (2,  'Alvenaria/Tijolo',                     'Canais ou caixas de passagem antigas'),
    (3,  'Ferro Fundido Cinzento (FoFo)',        'Redes antigas - Menor resistência que o Dúctil'),
    (4,  'Cobre',                                'Instalações prediais de água quente/fria'),
    (5,  'Concreto Simples (CS)',                'Galerias de águas pluviais/Esgoto por gravidade'),
    (6,  'Concreto Armado (CA)',                 'Adutoras de grande porte ou galerias - NBR 8890'),
    (7,  'Ferro Fundido Dúctil (FFD)',           'Padrão para adutoras e redes de pressão - NBR 7675'),
    (8,  'Aço Galvanizado',                      'Ramais prediais e combate a incêndio'),
    (9,  'Aço Carbono',                          'Grandes adutoras e obras de arte (pontes)'),
    (10, 'Polietileno de Alta Densidade (PEAD)', 'Ramais e redes flexíveis (MND) - NBR 15597'),
    (11, 'Polipropileno (PPR)',                  'Instalações prediais modernas (termofusão)'),
    (12, 'PVC Soldável (Marrom)',                'Uso predial interno - NBR 5648'),
    (13, 'PVC PBA (Classe 12/15)',               'Redes de distribuição de água - NBR 10355'),
    (14, 'PVC Defofort',                         'Redes de adução e distribuição (parede interna lisa)'),
    (15, 'PVC Orizon (Biorientado)',             'PVC-O - Alta resistência à pressão e impactos'),
    (16, 'CPVC',                                 'Policloreto de Vinila Clorado - Água quente'),
    (17, 'PRFV',                                 'Poliéster Reforçado com Fibra de Vidro - Grandes diâmetros'),
    (18, 'Concreto Protendido (PCCP)',           'Adutoras de altíssima pressão com cilindro de aço'),
    (19, 'Cerâmica/Vidrado',                     'Antigas redes de esgoto (raro em água)'),
    (20, 'Chumbo',                               'Obsoleto - Encontrado apenas em redes secularíssimas'),
    (21, 'Polietileno (PE)',                     'Uso geral em tubos flexíveis'),
    (22, 'Madeira/Stave Pipe',                   'Histórico/Industrial muito antigo');
